name: Create a Moment
description: Create a new moment post for the blog
title: "[Moment] "
labels: ["moment"]
body:
  - type: textarea
    id: content
    attributes:
      label: Content
      description: The content of your moment (supports Markdown)
      placeholder: |
        Write your moment here. You can use Markdown formatting.

        For images, you can either:
        - Paste them directly (they'll be uploaded to GitHub)
        - Use the media shortcode: {{< media src="image.jpg" caption="Caption" >}}
    validations:
      required: true

  - type: input
    id: location
    attributes:
      label: Location
      description: Where is this moment from?
      placeholder: "e.g., Beijing"
    validations:
      required: false

  - type: input
    id: mood
    attributes:
      label: Mood
      description: What's your mood?
      placeholder: "e.g., Happy, Cozy, Zen-like"
    validations:
      required: false
